### ISSUE TITLE
Google Charts not loading

### ISSUE THREAD

**Issue by ghost** [beranek1/webanalytics#7]
When I check the javascript console, there is no problem with the requesting of the API. But the charts simply won't load.

https://gyazo.com/46d7a0ce272c8295073fd9e86b241068

Main Error:

`jsapi_compiled_default_module.js:182 Uncaught (in promise) Error: Row 1 given with size different than 3 (the number of columns in the table).
    at gvjs_N.gvjs_.GZ (jsapi_compiled_default_module.js:182)
    at gvjs_N.gvjs_.Sp (jsapi_compiled_default_module.js:183)
    at drawobyrChart ((index):224)
    at drawCharts ((index):301)`

**Comment by beranek1** [comment]
I'll look into that, thanks for reporting.

**Comment by ghost** [comment]
Thanks.

**Comment by beranek1** [comment]
Could you check whether the problem still occurs with the lastest version? I've not been able to reproduce the issue and I think it might got resolved by the changes I made to the statistics page about a month ago.

**Comment by ghost** [comment]
Sure, I'll be able to in a day or two.

**Comment by beranek1** [comment]
Bug reporter does apparently no longer exist and the bug does no longer occur.
