### ISSUE TITLE
invalid arument supplied for foreach php web analytics

### ISSUE THREAD

**Issue by riazahmadshigri** [beranek1/webanalytics#8]
iam getting following errror in  when i run both /webstatistics.php and webanalytics.php  through browser im trying to convert it to mysqli oop
Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\project_adventure\webstatistics.php on line 747
Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\project_adventure\webanalytics.php on line 79
statement: at this line
  function get_one_row($query) {
        foreach ($this->query($query) as $row) {
            return $row;
        }
        return null;
    }

as i have checked in pdo working like charm but theres a little issue when webanalytics.php is included in header portion as header is included in all pages  and runs webstatistic.php  request value double increament and in page visiter section it shows 404 page is requested as 404 is a page in root of my web   but strange thing is this that request value also increaments for also those pages which doesnt include webanalytics.php 
this occurs when auto run is true but if autorun is false and include shortcode on different pages everything works but in webstatistics.php it gives some errors
 Notice: Undefined index: os in /home/chogzmrn/public_html/admin/index.php on line 186
Notice: Trying to access array offset on value of type null in /home/chogzmrn/public_html/admin/index.php on line 186

i have webanalytics in root folder and webstatistics renamed to index.php is inside admin folder

**Comment by kernrot** [comment]
change `function get_one_row` at line 77 fixes the error, looks like the pdo result is not iterable?

```
    function get_one_row($query) {
        $result = $this->query($query);
        if($result) foreach ($result as $row) {
            return $row;
        }
        return null;
    }
```
